all:
  children:
    servidores:
      hosts:
        vagrant1:
          ansible_host: 192.168.10.20
          ansible_user: vagrant
          ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa
