- name: Configurar WordPress en CentOS
  hosts: vagrant1
  become: yes
  vars:
    php_packages:
      - php
      - php-mysqlnd
      - php-gd
    wordpress_url: https://wordpress.org/latest.tar.gz
    wordpress_dest: /var/www/html
    wp_config_file: /var/www/html/wp-config.php

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted

  tasks:
    - name: Instalar Apache y PHP
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ php_packages + ['httpd'] }}"
      notify: restart httpd

    - name: Iniciar y habilitar Apache
      service:
        name: httpd
        state: started
        enabled: true

    - name: Crear archivo info.php
      copy:
        dest: /var/www/html/info.php
        content: "<?php phpinfo(); ?>"
      notify: restart httpd

    - name: Descargar y extraer WordPress
      get_url:
        url: "{{ wordpress_url }}"
        dest: /tmp/latest.tar.gz

    - name: Descomprimir WordPress
      unarchive:
        src: /tmp/latest.tar.gz
        dest: "{{ wordpress_dest }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Cambiar permisos y ownership
      file:
        path: "{{ wordpress_dest }}"
        owner: apache
        group: apache
        mode: '0755'
        recurse: yes

    - name: Copiar wp-config
      copy:
        src: "{{ wordpress_dest }}/wp-config-sample.php"
        dest: "{{ wp_config_file }}"
        remote_src: yes

    - name: Editar configuración WordPress
      replace:
        path: "{{ wp_config_file }}"
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - { regexp: "define\\('DB_NAME',\\s*'[^']*'\\);", replace: "define('DB_NAME', 'wordpress');" }
        - { regexp: "define\\('DB_USER',\\s*'[^']*'\\);", replace: "define('DB_USER', 'wordpress');" }
        - { regexp: "define\\('DB_PASSWORD',\\s*'[^']*'\\);", replace: "define('DB_PASSWORD', '1234');" }
        - { regexp: "define\\('DB_HOST',\\s*'[^']*'\\);", replace: "define('DB_HOST', 'vagrant2');" }
      notify: restart httpd
